# Generated by Django 5.1.3 on 2024-12-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("API", "0002_delete_hospitals_delete_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
