# Generated by Django 5.1.3 on 2024-12-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hospitals",
        ),
    ]
