# Generated by Django 5.1.3 on 2024-12-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0005_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitals",
            name="insurance",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
