# Generated by Django 5.1.6 on 2025-04-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0006_hospitals_insurance"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitals",
            name="address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="hospitals",
            name="city",
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name="hospitals",
            name="phone",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="hospitals",
            name="services",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
