# Generated by Django 5.1.6 on 2025-04-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0007_hospitals_address_hospitals_city_hospitals_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitals",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hospitals",
            name="services",
            field=models.TextField(blank=True, null=True),
        ),
    ]
