# Generated by Django 5.1.6 on 2025-04-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0008_alter_hospitals_address_alter_hospitals_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitals",
            name="medical_class",
            field=models.CharField(default="بیمارستان", max_length=256),
        ),
    ]
