"""
Django settings for djangoProject project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# CELERY_BROKER_URL = 'redis://:sf9GhNenhIXROtNqRFmaANXtJQHyQ5Pw@redis-16244.c311.eu-central-1-1.ec2.redns.redis-cloud.com:16244'  
# CELERY_RESULT_BACKEND = 'redis://:sf9GhNenhIXROtNqRFmaANXtJQHyQ5Pw@redis-16244.c311.eu-central-1-1.ec2.redns.redis-cloud.com:16244'
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# redis_client = redis.Redis(..., ssl=True, ssl_cert_reqs=None)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-y*ty#&jtx*6-8v9906v43rb4vwxg3p62_$_ye!-^v!ugldbxji"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'loggers': {
        # Your app's logger
        'your_app_name': {  # Replace with your app name
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    # local apps
    "API",
    
    # third party apps 
    'adrf',
    'sslserver',
    'django_extensions',
    'corsheaders',

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

CORS_ALLOWED_ORIGINS = ["https://*" , "http://*"]
CORS_ALLOW_CREDENTIALS = True


ROOT_URLCONF = "djangoProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "djangoProject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
CORS_ALLOW_ALL_ORIGINS = True


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
   "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": "media",
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

NESHAN_API_KEY = "service.124861c588224f8490375c4d80207e14"
MAP_IR_API_KEY ="eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjUzYjMwNjhmOWMyNjhmMmFiZGYyNmY3NDAwNjc5Y2YwMWExMzkzMzI2Mjg0Yzg2MzQxNjc5OGQ3NGFmM2FmMmM1ZGJhMTdmMDM0OTYzZjI3In0.eyJhdWQiOiIzMTY5OSIsImp0aSI6IjUzYjMwNjhmOWMyNjhmMmFiZGYyNmY3NDAwNjc5Y2YwMWExMzkzMzI2Mjg0Yzg2MzQxNjc5OGQ3NGFmM2FmMmM1ZGJhMTdmMDM0OTYzZjI3IiwiaWF0IjoxNzQzMTc4OTYzLCJuYmYiOjE3NDMxNzg5NjMsImV4cCI6MTc0NTc3MDk2Mywic3ViIjoiIiwic2NvcGVzIjpbImJhc2ljIl19.RF6nrZU2a1egkstjcYC1JHE9C7SJKlJx_EzDNJdzFV3VT1glQguFY2tw9mzQ8cOZjyKGjtswSnYZN-I3vU3f0oPX0IBaV7KT57yMrKPANtY6KFwm717qdJNGImQ7Gbasu57Kx7UoColC9zZuu_t97Ne4UA43OQoEGPAaWwFrhkUZtorzPgoMemkIzTE9etVbB6xrIZ5lJxs0IP48SPMPpWJ-5yd73zz8Go0ilckry4j3cAOhXzLIlrGASSeJHws_W3z2dqVQkTO46i9ECDVtQfiyMZKc8GvoJAcZhwMj8uV4oi3_mlfkDLwMM-Nb55adloGNZABI-uIhPMsGfT53rQ"
